services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: 'youshallnotpass'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    labels:
      - "traefik.http.routers.pihole.rule=Host(`pihole.home`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=websecure"
    networks:
      web:  
      macvlan_net:
        ipv4_address: 10.0.0.100  # Static LAN IP for Pi-hole
      internal_net:
        ipv4_address: 192.168.100.2  # Static IP for host access

networks:
  web:
    external: true  


  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
          aux_addresses:
            host: 10.0.0.200

  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24  # Internal Docker network