services:
  tailscaled:
    image: tailscale/tailscale
    container_name: tailscaled
    environment:
      - TS_ROUTES=10.0.0.0/24
      - TS_AUTHKEY=tskey-auth-youshallnotpass
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale/
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
