services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command:
     - --api.insecure=true 
     - --providers.docker
     - --providers.docker.network=web
     - --providers.file.directory=/etc/traefik/dynamic
     - --entryPoints.web.address=:80
     - --entryPoints.websecure.address=:443
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"

    restart: unless-stopped

    networks:
      - web
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the dynamic configuration
      - /root/certs-traefik.yml:/etc/traefik/dynamic/certs-traefik.yaml
      # Mount the directory containing the certs
      - /root/certs/:/etc/certs/
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.home`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.entrypoints=websecure"

networks:
  web:
    external: true